#!/bin/bash

BBLK="\033[1;30m"

BRED="\033[1;31m"
BGRN="\033[1;32m"
BYEL="\033[1;33m"
BMAG="\033[1;35m"

CRESET='\033[0m'


FLAG_FILE=".git/clang_warned"

OUT=$(git-clang-format --diff --staged)
FORMAT_WARN=0

if ! echo "$OUT" | grep -q "not modify"; then

    if [ ! -f "$FLAG_FILE" ]; then
        echo -e "\n${BBLK}==================================================${CRESET}"
        echo -e "[${BBLK}pre-commit${CRESET}] ${BYEL}Suggested clang formatting ${CRESET}"
        echo -e "[${BBLK}pre-commit${CRESET}] ${BMAG}clang-format -i src/* include/*${CRESET}"
        echo -e "[${BBLK}pre-commit${CRESET}] ${BYEL}You can commit again to ignore this warning ${CRESET}"
        echo -e "${BBLK}==================================================${CRESET}\n"

        echo -e "$OUT"
        touch "$FLAG_FILE"
        FORMAT_WARN=1
    else
        echo -e "\n${BBLK}==================================================${CRESET}"
        echo -e "[${BBLK}pre-commit${CRESET}] ${BYEL}Skipped clang formatting ${CRESET}"
        echo -e "${BBLK}==================================================${CRESET}\n"

        echo -e "$OUT"
        rm -f "$FLAG_FILE"
    fi

else
    echo -e "\n${BBLK}==================================================${CRESET}"
    echo -e "[${BBLK}pre-commit${CRESET}] ${BGRN}Clang formatting is good ${CRESET}"
    echo -e "${BBLK}==================================================${CRESET}"
    rm -f "$FLAG_FILE"
fi


# echo -e "[${BBLK}pre-commit${CRESET}] ${BYEL}Re-compiling project...${CRESET}"
make fclean > /dev/null 2>&1

if ! make -j$(nproc) > /dev/null 2>&1; then
    echo -e "\n${BBLK}==================================================${CRESET}"
    echo -e "[${BBLK}pre-commit${CRESET}] ${BRED}Compilation error ${CRESET}"
    echo -e "${BBLK}==================================================${CRESET}\n"
    make

    rm -f "$FLAG_FILE"

    exit 1
fi

echo -e "\n${BBLK}==================================================${CRESET}"
echo -e "[${BBLK}pre-commit${CRESET}] ${BGRN}Compilation successful ${CRESET}"
echo -e "${BBLK}==================================================${CRESET}\n"

if [ "$FORMAT_WARN" -eq 1 ]; then
    exit 1
fi
